-- ============================================================================
-- CONSOLIDATED INITIAL MIGRATION
-- Generated by combining 25 individual migration files in chronological order
-- ============================================================================


-- ============================================================================
-- Migration 1: 20251221171524_be5668d9-5226-40b3-8f0d-e3d063809322.sql
-- ============================================================================

-- Create app_role enum for user roles
CREATE TYPE public.app_role AS ENUM ('parent', 'child');

-- Create profiles table (linked to auth.users)
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL UNIQUE,
  email TEXT,
  full_name TEXT,
  avatar_url TEXT,
  language_preference TEXT DEFAULT 'ru' CHECK (language_preference IN ('ru', 'en')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Create user_roles table (separate from profiles for security)
CREATE TABLE public.user_roles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  role app_role NOT NULL,
  UNIQUE (user_id, role)
);

-- Create families table
CREATE TABLE public.families (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL DEFAULT 'Моя семья',
  timezone TEXT DEFAULT 'Europe/Moscow',
  default_language TEXT DEFAULT 'ru' CHECK (default_language IN ('ru', 'en')),
  currency_name TEXT DEFAULT 'Coins',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Create children table
CREATE TABLE public.children (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  family_id UUID REFERENCES public.families(id) ON DELETE CASCADE NOT NULL,
  linked_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  avatar_url TEXT DEFAULT '🦁',
  language_preference TEXT DEFAULT 'ru' CHECK (language_preference IN ('ru', 'en')),
  balance INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Create task_templates table
CREATE TABLE public.task_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  family_id UUID REFERENCES public.families(id) ON DELETE CASCADE NOT NULL,
  child_id UUID REFERENCES public.children(id) ON DELETE CASCADE,
  title_ru TEXT NOT NULL,
  title_en TEXT NOT NULL,
  description_ru TEXT,
  description_en TEXT,
  icon TEXT DEFAULT '✨',
  reward_amount INTEGER NOT NULL DEFAULT 5,
  task_type TEXT NOT NULL DEFAULT 'one_time' CHECK (task_type IN ('one_time', 'recurring')),
  one_time_date DATE,
  recurring_rule TEXT CHECK (recurring_rule IN ('daily', 'weekly', 'monthly')),
  recurring_days INTEGER[] DEFAULT '{}',
  recurring_time TIME DEFAULT '09:00',
  start_date DATE NOT NULL DEFAULT CURRENT_DATE,
  end_date DATE,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Create task_instances table
CREATE TABLE public.task_instances (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  template_id UUID REFERENCES public.task_templates(id) ON DELETE CASCADE NOT NULL,
  child_id UUID REFERENCES public.children(id) ON DELETE CASCADE NOT NULL,
  due_datetime TIMESTAMPTZ NOT NULL,
  state TEXT NOT NULL DEFAULT 'todo' CHECK (state IN ('todo', 'doing', 'done', 'skipped', 'cancelled')),
  completed_at TIMESTAMPTZ,
  reward_granted BOOLEAN NOT NULL DEFAULT false,
  cancellation_scope TEXT CHECK (cancellation_scope IN ('this_only', 'this_and_future')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Create transactions table
CREATE TABLE public.transactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  family_id UUID REFERENCES public.families(id) ON DELETE CASCADE NOT NULL,
  child_id UUID REFERENCES public.children(id) ON DELETE CASCADE NOT NULL,
  transaction_type TEXT NOT NULL CHECK (transaction_type IN ('earn', 'adjust', 'spend', 'refund')),
  amount INTEGER NOT NULL,
  source TEXT CHECK (source IN ('task_instance', 'manual', 'store_purchase', 'job_claim')),
  source_id UUID,
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Create store_items table
CREATE TABLE public.store_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  family_id UUID REFERENCES public.families(id) ON DELETE CASCADE NOT NULL,
  name_ru TEXT NOT NULL,
  name_en TEXT NOT NULL,
  description_ru TEXT,
  description_en TEXT,
  price INTEGER NOT NULL,
  image_url TEXT DEFAULT '🎁',
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Create purchases table
CREATE TABLE public.purchases (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  family_id UUID REFERENCES public.families(id) ON DELETE CASCADE NOT NULL,
  child_id UUID REFERENCES public.children(id) ON DELETE CASCADE NOT NULL,
  store_item_id UUID REFERENCES public.store_items(id) ON DELETE SET NULL,
  price_at_purchase INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'requested' CHECK (status IN ('requested', 'approved', 'delivered', 'cancelled')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Create job_board_items table
CREATE TABLE public.job_board_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  family_id UUID REFERENCES public.families(id) ON DELETE CASCADE NOT NULL,
  title_ru TEXT NOT NULL,
  title_en TEXT NOT NULL,
  description_ru TEXT,
  description_en TEXT,
  icon TEXT DEFAULT '💼',
  reward_amount INTEGER NOT NULL,
  active BOOLEAN NOT NULL DEFAULT true,
  availability TEXT DEFAULT 'always' CHECK (availability IN ('always', 'once', 'limited')),
  available_count INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Create job_claims table
CREATE TABLE public.job_claims (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  job_board_item_id UUID REFERENCES public.job_board_items(id) ON DELETE CASCADE NOT NULL,
  child_id UUID REFERENCES public.children(id) ON DELETE CASCADE NOT NULL,
  claimed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  status TEXT NOT NULL DEFAULT 'claimed' CHECK (status IN ('claimed', 'done', 'cancelled')),
  linked_task_instance_id UUID REFERENCES public.task_instances(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Create activity_schedules table
CREATE TABLE public.activity_schedules (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  family_id UUID REFERENCES public.families(id) ON DELETE CASCADE NOT NULL,
  child_id UUID REFERENCES public.children(id) ON DELETE CASCADE NOT NULL,
  title_ru TEXT NOT NULL,
  title_en TEXT NOT NULL,
  location TEXT,
  recurring_rule TEXT DEFAULT 'weekly' CHECK (recurring_rule IN ('daily', 'weekly', 'monthly')),
  recurring_days INTEGER[] DEFAULT '{}',
  time TIME NOT NULL,
  duration INTEGER NOT NULL DEFAULT 60,
  start_date DATE NOT NULL DEFAULT CURRENT_DATE,
  end_date DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.families ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.children ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_instances ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.store_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.job_board_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.job_claims ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_schedules ENABLE ROW LEVEL SECURITY;

-- Create security definer function to check if user is family owner
CREATE OR REPLACE FUNCTION public.is_family_owner(_user_id UUID, _family_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.families
    WHERE id = _family_id AND owner_user_id = _user_id
  )
$$;

-- Create security definer function to check if user is linked child in family
CREATE OR REPLACE FUNCTION public.is_child_in_family(_user_id UUID, _family_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.children
    WHERE family_id = _family_id AND linked_user_id = _user_id
  )
$$;

-- Create security definer function to get user's family id (as owner)
CREATE OR REPLACE FUNCTION public.get_user_family_id(_user_id UUID)
RETURNS UUID
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT id FROM public.families WHERE owner_user_id = _user_id LIMIT 1
$$;

-- Create security definer function to get child's family id by linked user
CREATE OR REPLACE FUNCTION public.get_child_family_id(_user_id UUID)
RETURNS UUID
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT family_id FROM public.children WHERE linked_user_id = _user_id LIMIT 1
$$;

-- Create function to check family membership (owner or child)
CREATE OR REPLACE FUNCTION public.is_family_member(_user_id UUID, _family_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT public.is_family_owner(_user_id, _family_id) OR public.is_child_in_family(_user_id, _family_id)
$$;

-- RLS Policies for profiles
CREATE POLICY "Users can view their own profile"
ON public.profiles FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can update their own profile"
ON public.profiles FOR UPDATE
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own profile"
ON public.profiles FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- RLS Policies for user_roles
CREATE POLICY "Users can view their own roles"
ON public.user_roles FOR SELECT
USING (auth.uid() = user_id);

-- RLS Policies for families
CREATE POLICY "Family owners can view their families"
ON public.families FOR SELECT
USING (auth.uid() = owner_user_id);

CREATE POLICY "Family owners can update their families"
ON public.families FOR UPDATE
USING (auth.uid() = owner_user_id);

CREATE POLICY "Users can create families"
ON public.families FOR INSERT
WITH CHECK (auth.uid() = owner_user_id);

CREATE POLICY "Family owners can delete their families"
ON public.families FOR DELETE
USING (auth.uid() = owner_user_id);

-- RLS Policies for children
CREATE POLICY "Family owners can view children"
ON public.children FOR SELECT
USING (public.is_family_owner(auth.uid(), family_id));

CREATE POLICY "Linked children can view themselves"
ON public.children FOR SELECT
USING (auth.uid() = linked_user_id);

CREATE POLICY "Family owners can manage children"
ON public.children FOR ALL
USING (public.is_family_owner(auth.uid(), family_id));

-- RLS Policies for task_templates
CREATE POLICY "Family members can view task templates"
ON public.task_templates FOR SELECT
USING (public.is_family_member(auth.uid(), family_id));

CREATE POLICY "Family owners can manage task templates"
ON public.task_templates FOR ALL
USING (public.is_family_owner(auth.uid(), family_id));

-- RLS Policies for task_instances
CREATE POLICY "Family members can view task instances"
ON public.task_instances FOR SELECT
USING (
  EXISTS (
    SELECT 1 FROM public.task_templates tt
    WHERE tt.id = template_id AND public.is_family_member(auth.uid(), tt.family_id)
  )
);

CREATE POLICY "Family owners can manage task instances"
ON public.task_instances FOR ALL
USING (
  EXISTS (
    SELECT 1 FROM public.task_templates tt
    WHERE tt.id = template_id AND public.is_family_owner(auth.uid(), tt.family_id)
  )
);

CREATE POLICY "Children can update their own task instances"
ON public.task_instances FOR UPDATE
USING (
  EXISTS (
    SELECT 1 FROM public.children c
    WHERE c.id = child_id AND c.linked_user_id = auth.uid()
  )
);

-- RLS Policies for transactions
CREATE POLICY "Family members can view transactions"
ON public.transactions FOR SELECT
USING (public.is_family_member(auth.uid(), family_id));

CREATE POLICY "Family owners can manage transactions"
ON public.transactions FOR ALL
USING (public.is_family_owner(auth.uid(), family_id));

-- RLS Policies for store_items
CREATE POLICY "Family members can view store items"
ON public.store_items FOR SELECT
USING (public.is_family_member(auth.uid(), family_id));

CREATE POLICY "Family owners can manage store items"
ON public.store_items FOR ALL
USING (public.is_family_owner(auth.uid(), family_id));

-- RLS Policies for purchases
CREATE POLICY "Family members can view purchases"
ON public.purchases FOR SELECT
USING (public.is_family_member(auth.uid(), family_id));

CREATE POLICY "Family owners can manage purchases"
ON public.purchases FOR ALL
USING (public.is_family_owner(auth.uid(), family_id));

CREATE POLICY "Children can create purchases"
ON public.purchases FOR INSERT
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.children c
    WHERE c.id = child_id AND c.linked_user_id = auth.uid()
  )
);

-- RLS Policies for job_board_items
CREATE POLICY "Family members can view job board items"
ON public.job_board_items FOR SELECT
USING (public.is_family_member(auth.uid(), family_id));

CREATE POLICY "Family owners can manage job board items"
ON public.job_board_items FOR ALL
USING (public.is_family_owner(auth.uid(), family_id));

-- RLS Policies for job_claims
CREATE POLICY "Family members can view job claims"
ON public.job_claims FOR SELECT
USING (
  EXISTS (
    SELECT 1 FROM public.job_board_items jbi
    WHERE jbi.id = job_board_item_id AND public.is_family_member(auth.uid(), jbi.family_id)
  )
);

CREATE POLICY "Children can create job claims"
ON public.job_claims FOR INSERT
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.children c
    WHERE c.id = child_id AND c.linked_user_id = auth.uid()
  )
);

CREATE POLICY "Family owners can manage job claims"
ON public.job_claims FOR ALL
USING (
  EXISTS (
    SELECT 1 FROM public.job_board_items jbi
    WHERE jbi.id = job_board_item_id AND public.is_family_owner(auth.uid(), jbi.family_id)
  )
);

-- RLS Policies for activity_schedules
CREATE POLICY "Family members can view activity schedules"
ON public.activity_schedules FOR SELECT
USING (public.is_family_member(auth.uid(), family_id));

CREATE POLICY "Family owners can manage activity schedules"
ON public.activity_schedules FOR ALL
USING (public.is_family_owner(auth.uid(), family_id));

-- Create updated_at trigger function
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

-- Create triggers for updated_at
CREATE TRIGGER update_profiles_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_families_updated_at
  BEFORE UPDATE ON public.families
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_children_updated_at
  BEFORE UPDATE ON public.children
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_task_templates_updated_at
  BEFORE UPDATE ON public.task_templates
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_task_instances_updated_at
  BEFORE UPDATE ON public.task_instances
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_store_items_updated_at
  BEFORE UPDATE ON public.store_items
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_purchases_updated_at
  BEFORE UPDATE ON public.purchases
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_job_board_items_updated_at
  BEFORE UPDATE ON public.job_board_items
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_job_claims_updated_at
  BEFORE UPDATE ON public.job_claims
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_activity_schedules_updated_at
  BEFORE UPDATE ON public.activity_schedules
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Create trigger to auto-create profile on user signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (user_id, email, full_name)
  VALUES (new.id, new.email, new.raw_user_meta_data ->> 'full_name');

  -- Auto-assign parent role for new users
  INSERT INTO public.user_roles (user_id, role)
  VALUES (new.id, 'parent');

  RETURN new;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Create indexes for performance
CREATE INDEX idx_children_family_id ON public.children(family_id);
CREATE INDEX idx_children_linked_user_id ON public.children(linked_user_id);
CREATE INDEX idx_task_templates_family_id ON public.task_templates(family_id);
CREATE INDEX idx_task_templates_child_id ON public.task_templates(child_id);
CREATE INDEX idx_task_instances_template_id ON public.task_instances(template_id);
CREATE INDEX idx_task_instances_child_id ON public.task_instances(child_id);
CREATE INDEX idx_task_instances_due_datetime ON public.task_instances(due_datetime);
CREATE INDEX idx_task_instances_state ON public.task_instances(state);
CREATE INDEX idx_transactions_family_id ON public.transactions(family_id);
CREATE INDEX idx_transactions_child_id ON public.transactions(child_id);
CREATE INDEX idx_store_items_family_id ON public.store_items(family_id);
CREATE INDEX idx_purchases_family_id ON public.purchases(family_id);
CREATE INDEX idx_purchases_child_id ON public.purchases(child_id);
CREATE INDEX idx_job_board_items_family_id ON public.job_board_items(family_id);
CREATE INDEX idx_job_claims_job_board_item_id ON public.job_claims(job_board_item_id);
CREATE INDEX idx_job_claims_child_id ON public.job_claims(child_id);
CREATE INDEX idx_activity_schedules_family_id ON public.activity_schedules(family_id);
CREATE INDEX idx_activity_schedules_child_id ON public.activity_schedules(child_id);


-- ============================================================================
-- Migration 2: 20251221191935_ef6a8654-db0b-465b-a7f5-a651d091164e.sql
-- ============================================================================

-- Create wishlist table for children to mark desired store items
CREATE TABLE public.wishlists (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  child_id UUID NOT NULL REFERENCES public.children(id) ON DELETE CASCADE,
  store_item_id UUID NOT NULL REFERENCES public.store_items(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  UNIQUE(child_id, store_item_id)
);

-- Enable Row Level Security
ALTER TABLE public.wishlists ENABLE ROW LEVEL SECURITY;

-- Create policies for wishlist access
CREATE POLICY "Users can view wishlists in their family"
ON public.wishlists
FOR SELECT
USING (
  EXISTS (
    SELECT 1 FROM public.children c
    JOIN public.families f ON c.family_id = f.id
    WHERE c.id = wishlists.child_id
    AND (f.owner_user_id = auth.uid() OR c.linked_user_id = auth.uid())
  )
);

CREATE POLICY "Users can add to wishlist for their children or themselves"
ON public.wishlists
FOR INSERT
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.children c
    JOIN public.families f ON c.family_id = f.id
    WHERE c.id = wishlists.child_id
    AND (f.owner_user_id = auth.uid() OR c.linked_user_id = auth.uid())
  )
);

CREATE POLICY "Users can remove from wishlist"
ON public.wishlists
FOR DELETE
USING (
  EXISTS (
    SELECT 1 FROM public.children c
    JOIN public.families f ON c.family_id = f.id
    WHERE c.id = wishlists.child_id
    AND (f.owner_user_id = auth.uid() OR c.linked_user_id = auth.uid())
  )
);


-- ============================================================================
-- Migration 3: 20251221194540_fadd70e6-94d8-460e-b822-120eacbe9dc6.sql
-- ============================================================================

-- Add task_category column to distinguish between routine tasks and activities
ALTER TABLE public.task_templates
ADD COLUMN task_category text NOT NULL DEFAULT 'routine';

-- Add comment for clarity
COMMENT ON COLUMN public.task_templates.task_category IS 'Category of the task: routine (regular tasks) or activity (classes/activities that also appear in schedule)';


-- ============================================================================
-- Migration 4: 20251222153848_ebe48c72-b663-4004-8fcf-05a0d3db81f5.sql
-- ============================================================================

-- Add end_time column to task_templates for time interval support
ALTER TABLE public.task_templates
ADD COLUMN end_time time without time zone DEFAULT NULL;

-- Add comment for clarity
COMMENT ON COLUMN public.task_templates.end_time IS 'End time for task duration (optional). recurring_time serves as start time.';
COMMENT ON COLUMN public.task_templates.recurring_time IS 'Start time for task execution.';


-- ============================================================================
-- Migration 5: 20251222155940_9f5fa6c3-12ff-4ce3-b86a-347feb00604a.sql
-- ============================================================================

-- Create table for task steps (checklist items for templates)
CREATE TABLE public.task_steps (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  template_id UUID NOT NULL REFERENCES public.task_templates(id) ON DELETE CASCADE,
  title_ru TEXT NOT NULL,
  title_en TEXT NOT NULL,
  order_index INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Create table for tracking step completions per task instance
CREATE TABLE public.task_step_completions (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  task_instance_id UUID NOT NULL REFERENCES public.task_instances(id) ON DELETE CASCADE,
  step_id UUID NOT NULL REFERENCES public.task_steps(id) ON DELETE CASCADE,
  completed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  UNIQUE(task_instance_id, step_id)
);

-- Enable RLS
ALTER TABLE public.task_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_step_completions ENABLE ROW LEVEL SECURITY;

-- RLS policies for task_steps
CREATE POLICY "Family members can view task steps"
ON public.task_steps
FOR SELECT
USING (EXISTS (
  SELECT 1 FROM task_templates tt
  WHERE tt.id = task_steps.template_id
  AND is_family_member(auth.uid(), tt.family_id)
));

CREATE POLICY "Family owners can manage task steps"
ON public.task_steps
FOR ALL
USING (EXISTS (
  SELECT 1 FROM task_templates tt
  WHERE tt.id = task_steps.template_id
  AND is_family_owner(auth.uid(), tt.family_id)
));

-- RLS policies for task_step_completions
CREATE POLICY "Family members can view step completions"
ON public.task_step_completions
FOR SELECT
USING (EXISTS (
  SELECT 1 FROM task_instances ti
  JOIN task_templates tt ON tt.id = ti.template_id
  WHERE ti.id = task_step_completions.task_instance_id
  AND is_family_member(auth.uid(), tt.family_id)
));

CREATE POLICY "Family owners can manage step completions"
ON public.task_step_completions
FOR ALL
USING (EXISTS (
  SELECT 1 FROM task_instances ti
  JOIN task_templates tt ON tt.id = ti.template_id
  WHERE ti.id = task_step_completions.task_instance_id
  AND is_family_owner(auth.uid(), tt.family_id)
));

CREATE POLICY "Children can complete their own steps"
ON public.task_step_completions
FOR INSERT
WITH CHECK (EXISTS (
  SELECT 1 FROM task_instances ti
  JOIN children c ON c.id = ti.child_id
  WHERE ti.id = task_step_completions.task_instance_id
  AND c.linked_user_id = auth.uid()
));

CREATE POLICY "Children can delete their own step completions"
ON public.task_step_completions
FOR DELETE
USING (EXISTS (
  SELECT 1 FROM task_instances ti
  JOIN children c ON c.id = ti.child_id
  WHERE ti.id = task_step_completions.task_instance_id
  AND c.linked_user_id = auth.uid()
));

-- Add index for performance
CREATE INDEX idx_task_steps_template_id ON public.task_steps(template_id);
CREATE INDEX idx_task_step_completions_instance_id ON public.task_step_completions(task_instance_id);


-- ============================================================================
-- Migration 6: 20251222164049_55a2fe56-1a82-4b2e-8553-4ff9a7f07920.sql
-- ============================================================================

-- Add bonus and due date columns to task_steps
ALTER TABLE public.task_steps
ADD COLUMN due_date date DEFAULT NULL,
ADD COLUMN bonus_amount integer DEFAULT 0,
ADD COLUMN bonus_hidden boolean DEFAULT false;


-- ============================================================================
-- Migration 7: 20251222165002_fa72bb3f-2302-4de6-a136-7cb3a657aa3c.sql
-- ============================================================================

-- Create notifications table
CREATE TABLE public.notifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  family_id uuid NOT NULL REFERENCES public.families(id) ON DELETE CASCADE,
  recipient_type text NOT NULL DEFAULT 'parent', -- 'parent' or 'child'
  recipient_child_id uuid REFERENCES public.children(id) ON DELETE CASCADE,
  type text NOT NULL, -- 'step_completed', 'task_completed', 'purchase_requested', etc.
  title_ru text NOT NULL,
  title_en text NOT NULL,
  message_ru text,
  message_en text,
  data jsonb DEFAULT '{}',
  read_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Parents can view notifications for their family
CREATE POLICY "Family owners can view notifications"
ON public.notifications
FOR SELECT
USING (is_family_owner(auth.uid(), family_id) AND recipient_type = 'parent');

-- Parents can update (mark as read) their notifications
CREATE POLICY "Family owners can update notifications"
ON public.notifications
FOR UPDATE
USING (is_family_owner(auth.uid(), family_id) AND recipient_type = 'parent');

-- Allow inserting notifications (for triggers/app logic)
CREATE POLICY "Allow insert notifications"
ON public.notifications
FOR INSERT
WITH CHECK (is_family_member(auth.uid(), family_id));

-- Enable realtime for notifications
ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;

-- Create function to notify parent when step is completed
CREATE OR REPLACE FUNCTION public.notify_step_completion()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_family_id uuid;
  v_child_name text;
  v_step_title_ru text;
  v_step_title_en text;
  v_task_title_ru text;
  v_task_title_en text;
  v_step_bonus integer;
BEGIN
  -- Get task instance details
  SELECT
    tt.family_id,
    c.name,
    ts.title_ru,
    ts.title_en,
    tt.title_ru,
    tt.title_en,
    ts.bonus_amount
  INTO
    v_family_id,
    v_child_name,
    v_step_title_ru,
    v_step_title_en,
    v_task_title_ru,
    v_task_title_en,
    v_step_bonus
  FROM task_instances ti
  JOIN task_templates tt ON tt.id = ti.template_id
  JOIN children c ON c.id = ti.child_id
  JOIN task_steps ts ON ts.id = NEW.step_id
  WHERE ti.id = NEW.task_instance_id;

  -- Insert notification for parent
  INSERT INTO public.notifications (
    family_id,
    recipient_type,
    type,
    title_ru,
    title_en,
    message_ru,
    message_en,
    data
  ) VALUES (
    v_family_id,
    'parent',
    'step_completed',
    v_child_name || ' выполнил шаг',
    v_child_name || ' completed a step',
    '«' || v_step_title_ru || '» в задаче «' || v_task_title_ru || '»',
    '"' || v_step_title_en || '" in task "' || v_task_title_en || '"',
    jsonb_build_object(
      'child_name', v_child_name,
      'step_title_ru', v_step_title_ru,
      'step_title_en', v_step_title_en,
      'task_title_ru', v_task_title_ru,
      'task_title_en', v_task_title_en,
      'bonus_amount', v_step_bonus,
      'task_instance_id', NEW.task_instance_id,
      'step_id', NEW.step_id
    )
  );

  RETURN NEW;
END;
$$;

-- Create trigger for step completion
CREATE TRIGGER on_step_completion
AFTER INSERT ON public.task_step_completions
FOR EACH ROW
EXECUTE FUNCTION public.notify_step_completion();


-- ============================================================================
-- Migration 8: 20251222175232_350edd72-0d3c-4a35-9617-7303825595a2.sql
-- ============================================================================

-- Create function to grant step bonus
CREATE OR REPLACE FUNCTION public.grant_step_bonus()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_child_id uuid;
  v_family_id uuid;
  v_bonus_amount integer;
  v_step_title_ru text;
  v_step_title_en text;
BEGIN
  -- Get step bonus amount and task instance details
  SELECT
    ti.child_id,
    tt.family_id,
    COALESCE(ts.bonus_amount, 0),
    ts.title_ru,
    ts.title_en
  INTO
    v_child_id,
    v_family_id,
    v_bonus_amount,
    v_step_title_ru,
    v_step_title_en
  FROM task_instances ti
  JOIN task_templates tt ON tt.id = ti.template_id
  JOIN task_steps ts ON ts.id = NEW.step_id
  WHERE ti.id = NEW.task_instance_id;

  -- Only proceed if there's a bonus to grant
  IF v_bonus_amount > 0 THEN
    -- Update child balance
    UPDATE public.children
    SET balance = balance + v_bonus_amount
    WHERE id = v_child_id;

    -- Create transaction record
    INSERT INTO public.transactions (
      family_id,
      child_id,
      amount,
      transaction_type,
      source,
      source_id,
      note
    ) VALUES (
      v_family_id,
      v_child_id,
      v_bonus_amount,
      'earn',
      'step_bonus',
      NEW.step_id,
      'Бонус за шаг: ' || v_step_title_ru
    );
  END IF;

  RETURN NEW;
END;
$$;

-- Create trigger for step bonus
CREATE TRIGGER on_step_completion_grant_bonus
  AFTER INSERT ON public.task_step_completions
  FOR EACH ROW
  EXECUTE FUNCTION public.grant_step_bonus();


-- ============================================================================
-- Migration 9: 20251222181606_0503d6ff-a931-4ffe-9703-7c6b9ad8c4e2.sql
-- ============================================================================

-- Create function to refund step bonus on completion deletion
CREATE OR REPLACE FUNCTION public.refund_step_bonus()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_child_id uuid;
  v_family_id uuid;
  v_bonus_amount integer;
  v_step_title_ru text;
BEGIN
  -- Get step bonus amount and task instance details
  SELECT
    ti.child_id,
    tt.family_id,
    COALESCE(ts.bonus_amount, 0),
    ts.title_ru
  INTO
    v_child_id,
    v_family_id,
    v_bonus_amount,
    v_step_title_ru
  FROM task_instances ti
  JOIN task_templates tt ON tt.id = ti.template_id
  JOIN task_steps ts ON ts.id = OLD.step_id
  WHERE ti.id = OLD.task_instance_id;

  -- Only proceed if there was a bonus to refund
  IF v_bonus_amount > 0 THEN
    -- Subtract from child balance
    UPDATE public.children
    SET balance = balance - v_bonus_amount
    WHERE id = v_child_id;

    -- Create refund transaction record
    INSERT INTO public.transactions (
      family_id,
      child_id,
      amount,
      transaction_type,
      source,
      source_id,
      note
    ) VALUES (
      v_family_id,
      v_child_id,
      -v_bonus_amount,
      'adjustment',
      'step_bonus_refund',
      OLD.step_id,
      'Отмена шага: ' || v_step_title_ru
    );
  END IF;

  RETURN OLD;
END;
$$;

-- Create trigger for step bonus refund
CREATE TRIGGER on_step_completion_delete_refund_bonus
  BEFORE DELETE ON public.task_step_completions
  FOR EACH ROW
  EXECUTE FUNCTION public.refund_step_bonus();


-- ============================================================================
-- Migration 10: 20251222211151_a1df8ca8-ec43-4448-a890-c38984b4b2f0.sql
-- ============================================================================

-- Add duration field for step execution time
ALTER TABLE public.task_steps
ADD COLUMN duration_minutes INTEGER DEFAULT NULL;

COMMENT ON COLUMN public.task_steps.duration_minutes IS 'Estimated time to complete the step in minutes';


-- ============================================================================
-- Migration 11: 20251223121331_daa874e7-f857-4468-9c44-1186c183f377.sql
-- ============================================================================

-- Drop the existing SELECT policy that doesn't require authentication
DROP POLICY IF EXISTS "Users can view their own profile" ON public.profiles;

-- Create a new SELECT policy that requires authentication AND restricts to own profile
CREATE POLICY "Users can view their own profile"
ON public.profiles
FOR SELECT
USING (auth.uid() IS NOT NULL AND auth.uid() = user_id);


-- ============================================================================
-- Migration 12: 20251223122158_382b149e-3b79-478d-9bb8-d0ecea0afd7c.sql
-- ============================================================================

-- Drop existing SELECT policy
DROP POLICY IF EXISTS "Users can view their own profile" ON public.profiles;

-- Create SELECT policy with explicit authentication check
CREATE POLICY "Users can view their own profile"
ON public.profiles
FOR SELECT
TO authenticated
USING (auth.uid() = user_id);


-- ============================================================================
-- Migration 13: 20251223123840_53a2bcfb-dd5c-45bd-a3e4-d62698099762.sql
-- ============================================================================

-- =====================================================
-- PART 1: Database constraints for input validation (defense in depth)
-- =====================================================

-- Children table constraints
ALTER TABLE public.children
  ADD CONSTRAINT children_name_length CHECK (char_length(name) <= 100);

ALTER TABLE public.children
  ADD CONSTRAINT children_balance_range CHECK (balance >= -1000000 AND balance <= 10000000);

-- Task templates constraints
ALTER TABLE public.task_templates
  ADD CONSTRAINT task_templates_title_length CHECK (char_length(title_ru) <= 200 AND char_length(title_en) <= 200);

ALTER TABLE public.task_templates
  ADD CONSTRAINT task_templates_description_length CHECK (char_length(COALESCE(description_ru, '')) <= 1000 AND char_length(COALESCE(description_en, '')) <= 1000);

ALTER TABLE public.task_templates
  ADD CONSTRAINT task_templates_reward_range CHECK (reward_amount >= 0 AND reward_amount <= 10000);

-- Store items constraints
ALTER TABLE public.store_items
  ADD CONSTRAINT store_items_name_length CHECK (char_length(name_ru) <= 200 AND char_length(name_en) <= 200);

ALTER TABLE public.store_items
  ADD CONSTRAINT store_items_price_range CHECK (price >= 1 AND price <= 1000000);

-- Job board items constraints
ALTER TABLE public.job_board_items
  ADD CONSTRAINT job_board_items_title_length CHECK (char_length(title_ru) <= 200 AND char_length(title_en) <= 200);

ALTER TABLE public.job_board_items
  ADD CONSTRAINT job_board_items_description_length CHECK (char_length(COALESCE(description_ru, '')) <= 1000 AND char_length(COALESCE(description_en, '')) <= 1000);

ALTER TABLE public.job_board_items
  ADD CONSTRAINT job_board_items_reward_range CHECK (reward_amount >= 0 AND reward_amount <= 10000);

-- Activity schedules constraints
ALTER TABLE public.activity_schedules
  ADD CONSTRAINT activity_schedules_title_length CHECK (char_length(title_ru) <= 200 AND char_length(title_en) <= 200);

ALTER TABLE public.activity_schedules
  ADD CONSTRAINT activity_schedules_location_length CHECK (char_length(COALESCE(location, '')) <= 500);

ALTER TABLE public.activity_schedules
  ADD CONSTRAINT activity_schedules_duration_range CHECK (duration >= 5 AND duration <= 1440);

-- Transactions constraints
ALTER TABLE public.transactions
  ADD CONSTRAINT transactions_note_length CHECK (char_length(COALESCE(note, '')) <= 500);

-- Task steps constraints
ALTER TABLE public.task_steps
  ADD CONSTRAINT task_steps_title_length CHECK (char_length(title_ru) <= 200 AND char_length(title_en) <= 200);

ALTER TABLE public.task_steps
  ADD CONSTRAINT task_steps_bonus_range CHECK (COALESCE(bonus_amount, 0) >= 0 AND COALESCE(bonus_amount, 0) <= 10000);

-- =====================================================
-- PART 2: Atomic balance operation functions (race condition fix)
-- =====================================================

-- Function to complete a task atomically
CREATE OR REPLACE FUNCTION public.complete_task_with_reward(
  p_instance_id UUID,
  p_child_id UUID
) RETURNS json
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  v_reward INTEGER;
  v_family_id UUID;
  v_current_state TEXT;
  v_reward_granted BOOLEAN;
BEGIN
  -- Get task instance details with lock
  SELECT ti.state, ti.reward_granted, tt.reward_amount, tt.family_id
  INTO v_current_state, v_reward_granted, v_reward, v_family_id
  FROM task_instances ti
  JOIN task_templates tt ON ti.template_id = tt.id
  WHERE ti.id = p_instance_id AND ti.child_id = p_child_id
  FOR UPDATE;

  -- Validate state
  IF v_current_state IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'Task instance not found');
  END IF;

  IF v_current_state = 'done' THEN
    RETURN json_build_object('success', false, 'error', 'Task already completed');
  END IF;

  IF v_reward_granted THEN
    RETURN json_build_object('success', false, 'error', 'Reward already granted');
  END IF;

  -- Update task instance
  UPDATE task_instances
  SET state = 'done', completed_at = now(), reward_granted = true, updated_at = now()
  WHERE id = p_instance_id;

  -- Update child balance
  UPDATE children
  SET balance = balance + v_reward, updated_at = now()
  WHERE id = p_child_id;

  -- Create transaction record
  INSERT INTO transactions (family_id, child_id, transaction_type, amount, source, source_id)
  VALUES (v_family_id, p_child_id, 'earn', v_reward, 'task_instance', p_instance_id);

  RETURN json_build_object('success', true, 'reward', v_reward);
END;
$$;

-- Function to uncomplete a task atomically
CREATE OR REPLACE FUNCTION public.uncomplete_task_with_refund(
  p_instance_id UUID,
  p_child_id UUID
) RETURNS json
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  v_reward INTEGER;
  v_family_id UUID;
  v_current_state TEXT;
  v_reward_granted BOOLEAN;
BEGIN
  -- Get task instance details with lock
  SELECT ti.state, ti.reward_granted, tt.reward_amount, tt.family_id
  INTO v_current_state, v_reward_granted, v_reward, v_family_id
  FROM task_instances ti
  JOIN task_templates tt ON ti.template_id = tt.id
  WHERE ti.id = p_instance_id AND ti.child_id = p_child_id
  FOR UPDATE;

  -- Validate state
  IF v_current_state IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'Task instance not found');
  END IF;

  IF v_current_state != 'done' THEN
    RETURN json_build_object('success', false, 'error', 'Task not completed');
  END IF;

  -- Update task instance
  UPDATE task_instances
  SET state = 'todo', completed_at = NULL, reward_granted = false, updated_at = now()
  WHERE id = p_instance_id;

  -- Only refund if reward was granted
  IF v_reward_granted THEN
    -- Update child balance
    UPDATE children
    SET balance = balance - v_reward, updated_at = now()
    WHERE id = p_child_id;

    -- Create reversal transaction record
    INSERT INTO transactions (family_id, child_id, transaction_type, amount, source, source_id, note)
    VALUES (v_family_id, p_child_id, 'adjustment', -v_reward, 'task_instance', p_instance_id, 'Отмена выполнения задачи');
  END IF;

  RETURN json_build_object('success', true, 'refunded', v_reward_granted, 'amount', v_reward);
END;
$$;

-- Function to complete a job claim atomically
CREATE OR REPLACE FUNCTION public.complete_job_claim_with_reward(
  p_claim_id UUID,
  p_child_id UUID
) RETURNS json
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  v_reward INTEGER;
  v_family_id UUID;
  v_current_status TEXT;
  v_job_title TEXT;
BEGIN
  -- Get job claim details with lock
  SELECT jc.status, jbi.reward_amount, jbi.family_id, jbi.title_ru
  INTO v_current_status, v_reward, v_family_id, v_job_title
  FROM job_claims jc
  JOIN job_board_items jbi ON jc.job_board_item_id = jbi.id
  WHERE jc.id = p_claim_id AND jc.child_id = p_child_id
  FOR UPDATE;

  -- Validate state
  IF v_current_status IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'Job claim not found');
  END IF;

  IF v_current_status = 'done' THEN
    RETURN json_build_object('success', false, 'error', 'Job already completed');
  END IF;

  -- Update job claim status
  UPDATE job_claims
  SET status = 'done', updated_at = now()
  WHERE id = p_claim_id;

  -- Update child balance
  UPDATE children
  SET balance = balance + v_reward, updated_at = now()
  WHERE id = p_child_id;

  -- Create transaction record
  INSERT INTO transactions (family_id, child_id, transaction_type, amount, source, source_id, note)
  VALUES (v_family_id, p_child_id, 'earn', v_reward, 'job_claim', p_claim_id, 'Выполнена работа: ' || v_job_title);

  RETURN json_build_object('success', true, 'reward', v_reward);
END;
$$;

-- Function to purchase store item atomically
CREATE OR REPLACE FUNCTION public.purchase_store_item(
  p_item_id UUID,
  p_child_id UUID
) RETURNS json
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  v_price INTEGER;
  v_family_id UUID;
  v_child_balance INTEGER;
  v_item_name TEXT;
  v_item_active BOOLEAN;
  v_purchase_id UUID;
BEGIN
  -- Get store item details
  SELECT si.price, si.family_id, si.name_ru, si.active
  INTO v_price, v_family_id, v_item_name, v_item_active
  FROM store_items si
  WHERE si.id = p_item_id;

  IF v_price IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'Item not found');
  END IF;

  IF NOT v_item_active THEN
    RETURN json_build_object('success', false, 'error', 'Item not available');
  END IF;

  -- Get child balance with lock
  SELECT balance INTO v_child_balance
  FROM children
  WHERE id = p_child_id AND family_id = v_family_id
  FOR UPDATE;

  IF v_child_balance IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'Child not found');
  END IF;

  IF v_child_balance < v_price THEN
    RETURN json_build_object('success', false, 'error', 'Insufficient balance', 'balance', v_child_balance, 'price', v_price);
  END IF;

  -- Create purchase record
  INSERT INTO purchases (family_id, child_id, store_item_id, price_at_purchase, status)
  VALUES (v_family_id, p_child_id, p_item_id, v_price, 'requested')
  RETURNING id INTO v_purchase_id;

  -- Update child balance
  UPDATE children
  SET balance = balance - v_price, updated_at = now()
  WHERE id = p_child_id;

  -- Create transaction record
  INSERT INTO transactions (family_id, child_id, transaction_type, amount, source, source_id, note)
  VALUES (v_family_id, p_child_id, 'spend', -v_price, 'purchase', v_purchase_id, 'Покупка: ' || v_item_name);

  RETURN json_build_object('success', true, 'purchase_id', v_purchase_id, 'price', v_price);
END;
$$;

-- Function to adjust child balance atomically
CREATE OR REPLACE FUNCTION public.adjust_child_balance(
  p_child_id UUID,
  p_amount INTEGER,
  p_note TEXT DEFAULT NULL
) RETURNS json
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  v_family_id UUID;
  v_new_balance INTEGER;
  v_transaction_type TEXT;
BEGIN
  -- Get child with lock
  SELECT family_id INTO v_family_id
  FROM children
  WHERE id = p_child_id
  FOR UPDATE;

  IF v_family_id IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'Child not found');
  END IF;

  -- Determine transaction type
  v_transaction_type := CASE WHEN p_amount >= 0 THEN 'earn' ELSE 'spend' END;

  -- Update child balance
  UPDATE children
  SET balance = balance + p_amount, updated_at = now()
  WHERE id = p_child_id
  RETURNING balance INTO v_new_balance;

  -- Create transaction record
  INSERT INTO transactions (family_id, child_id, transaction_type, amount, source, note)
  VALUES (v_family_id, p_child_id, v_transaction_type, p_amount, 'manual', COALESCE(p_note, 'Ручная корректировка'));

  RETURN json_build_object('success', true, 'new_balance', v_new_balance);
END;
$$;


-- ============================================================================
-- Migration 14: 20260103142530_28645deb-da89-4b7c-bae7-830a8544dc1a.sql
-- ============================================================================

-- Create day_templates table for storing reusable day plans
CREATE TABLE public.day_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  family_id UUID REFERENCES public.families(id) ON DELETE CASCADE NOT NULL,
  name_ru TEXT NOT NULL,
  name_en TEXT NOT NULL,
  is_preset BOOLEAN NOT NULL DEFAULT false,
  preset_key TEXT, -- For preset templates: 'school_morning', 'after_school', etc.
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Create day_template_tasks table for tasks within a template
CREATE TABLE public.day_template_tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  day_template_id UUID REFERENCES public.day_templates(id) ON DELETE CASCADE NOT NULL,
  title_ru TEXT NOT NULL,
  title_en TEXT NOT NULL,
  description_ru TEXT,
  description_en TEXT,
  icon TEXT DEFAULT '✨',
  reward_amount INTEGER NOT NULL DEFAULT 5,
  time TEXT, -- e.g., '09:00' for ordering/display
  order_index INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.day_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.day_template_tasks ENABLE ROW LEVEL SECURITY;

-- RLS policies for day_templates
CREATE POLICY "Family members can view day templates"
ON public.day_templates
FOR SELECT
USING (is_family_member(auth.uid(), family_id));

CREATE POLICY "Family owners can manage day templates"
ON public.day_templates
FOR ALL
USING (is_family_owner(auth.uid(), family_id));

-- RLS policies for day_template_tasks
CREATE POLICY "Family members can view day template tasks"
ON public.day_template_tasks
FOR SELECT
USING (EXISTS (
  SELECT 1 FROM day_templates dt
  WHERE dt.id = day_template_tasks.day_template_id
  AND is_family_member(auth.uid(), dt.family_id)
));

CREATE POLICY "Family owners can manage day template tasks"
ON public.day_template_tasks
FOR ALL
USING (EXISTS (
  SELECT 1 FROM day_templates dt
  WHERE dt.id = day_template_tasks.day_template_id
  AND is_family_owner(auth.uid(), dt.family_id)
));

-- Add updated_at trigger
CREATE TRIGGER update_day_templates_updated_at
BEFORE UPDATE ON public.day_templates
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();


-- ============================================================================
-- Migration 15: 20260103163506_3a842d56-63a3-481b-bc67-d50d98b38588.sql
-- ============================================================================

-- Create template_events table for logging template applications
CREATE TABLE public.template_events (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  family_id UUID NOT NULL REFERENCES public.families(id) ON DELETE CASCADE,
  template_id UUID REFERENCES public.day_templates(id) ON DELETE SET NULL,
  preset_key TEXT,
  template_name TEXT NOT NULL,
  apply_mode TEXT NOT NULL CHECK (apply_mode IN ('replace', 'add')),
  apply_scope TEXT NOT NULL CHECK (apply_scope IN ('one_time', 'recurring')),
  target_date DATE NOT NULL,
  children_count INTEGER NOT NULL DEFAULT 1,
  tasks_created_count INTEGER NOT NULL DEFAULT 0,
  tasks_skipped_duplicates_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.template_events ENABLE ROW LEVEL SECURITY;

-- RLS policies
CREATE POLICY "Family owners can view template events"
ON public.template_events
FOR SELECT
USING (is_family_owner(auth.uid(), family_id));

CREATE POLICY "Family owners can insert template events"
ON public.template_events
FOR INSERT
WITH CHECK (is_family_owner(auth.uid(), family_id));

-- Create index for faster queries
CREATE INDEX idx_template_events_family_id ON public.template_events(family_id);
CREATE INDEX idx_template_events_created_at ON public.template_events(created_at DESC);


-- ============================================================================
-- Migration 16: 20260104082103_8283166f-0c74-4a2f-9961-cc4ef1f8dd04.sql
-- ============================================================================

-- Add optional child_id to store_items (null = available for all children)
ALTER TABLE public.store_items
ADD COLUMN IF NOT EXISTS child_id uuid REFERENCES public.children(id) ON DELETE SET NULL;

-- Add optional child_id to job_board_items (null = family-wide job)
ALTER TABLE public.job_board_items
ADD COLUMN IF NOT EXISTS child_id uuid REFERENCES public.children(id) ON DELETE SET NULL;

-- Create index for faster filtering
CREATE INDEX IF NOT EXISTS idx_store_items_child_id ON public.store_items(child_id);
CREATE INDEX IF NOT EXISTS idx_job_board_items_child_id ON public.job_board_items(child_id);


-- ============================================================================
-- Migration 17: 20260114011014_dcedc147-484c-409e-9fa0-6d6e22006a8b.sql
-- ============================================================================

-- Children can delete their own notifications
CREATE POLICY "Children can delete their notifications"
ON public.notifications
FOR DELETE
USING (
  recipient_type = 'child'
  AND EXISTS (
    SELECT 1 FROM public.children c
    WHERE c.id = notifications.recipient_child_id
    AND c.linked_user_id = auth.uid()
  )
);


-- ============================================================================
-- Migration 18: 20260114011609_872cbfe7-aa09-42a8-9b0a-cacd5a4b7a05.sql
-- ============================================================================

-- Drop the trigger that creates notifications on step completion
DROP TRIGGER IF EXISTS on_step_completion_notify ON public.task_step_completions;

-- We keep the notify_step_completion function but it won't be called anymore
-- The notifications table is kept for data integrity but won't receive new entries


-- ============================================================================
-- Migration 19: 20260114181411_9c8cd97b-e6b5-41af-b3f6-e5479bb51b91.sql
-- ============================================================================

-- Create family_members table for parent invites
CREATE TABLE public.family_members (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    family_id uuid NOT NULL REFERENCES public.families(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    role_label text NOT NULL DEFAULT 'Parent',
    permission_level text NOT NULL DEFAULT 'viewer' CHECK (permission_level IN ('viewer', 'admin')),
    invited_by uuid REFERENCES auth.users(id),
    invite_email text,
    invite_token uuid,
    invite_status text NOT NULL DEFAULT 'pending' CHECK (invite_status IN ('pending', 'accepted', 'declined')),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    UNIQUE (family_id, user_id)
);

-- Add allow_parent_activities column to families table for the toggle
ALTER TABLE public.families ADD COLUMN IF NOT EXISTS allow_parent_activities boolean NOT NULL DEFAULT false;

-- Enable RLS on family_members
ALTER TABLE public.family_members ENABLE ROW LEVEL SECURITY;

-- RLS policies for family_members
CREATE POLICY "Family owners can manage members"
ON public.family_members
FOR ALL
USING (EXISTS (
    SELECT 1 FROM public.families f
    WHERE f.id = family_members.family_id
    AND f.owner_user_id = auth.uid()
));

CREATE POLICY "Members can view their own membership"
ON public.family_members
FOR SELECT
USING (user_id = auth.uid());

CREATE POLICY "Admin members can manage family"
ON public.family_members
FOR ALL
USING (
    permission_level = 'admin'
    AND user_id = auth.uid()
);

-- Create index for faster lookups
CREATE INDEX idx_family_members_family_id ON public.family_members(family_id);
CREATE INDEX idx_family_members_user_id ON public.family_members(user_id);
CREATE INDEX idx_family_members_invite_token ON public.family_members(invite_token) WHERE invite_token IS NOT NULL;

-- Update updated_at trigger
CREATE TRIGGER update_family_members_updated_at
BEFORE UPDATE ON public.family_members
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();


-- ============================================================================
-- Migration 20: 20260114182256_b37496ea-c299-4c7d-abb5-413fb769366f.sql
-- ============================================================================

-- Create a public view without sensitive fields (invite_email, invite_token)
CREATE VIEW public.family_members_public
WITH (security_invoker=on) AS
SELECT
  id,
  family_id,
  user_id,
  invited_by,
  created_at,
  updated_at,
  role_label,
  permission_level,
  invite_status
FROM public.family_members;

-- Drop the existing policy that exposes sensitive data
DROP POLICY IF EXISTS "Members can view their own membership" ON public.family_members;

-- Create a new, more restrictive SELECT policy
-- Users can only view their own membership record (not pending invitations for others)
CREATE POLICY "Members can view their own membership record only"
ON public.family_members
FOR SELECT
USING (user_id = auth.uid());

-- Family owners can view all members including pending invitations (they need to manage invites)
CREATE POLICY "Family owners can view all family members"
ON public.family_members
FOR SELECT
USING (
  EXISTS (
    SELECT 1 FROM public.families f
    WHERE f.id = family_members.family_id AND f.owner_user_id = auth.uid()
  )
);

-- Add comment explaining the security pattern
COMMENT ON VIEW public.family_members_public IS 'Public view of family_members without sensitive fields (invite_email, invite_token). Use this view in application code for regular queries.';


-- ============================================================================
-- Migration 21: 20260114194717_1687675a-128e-4514-b360-8602ca77848a.sql
-- ============================================================================

-- Add routine_type column to distinguish morning vs evening routines
ALTER TABLE public.task_templates
ADD COLUMN routine_type text DEFAULT NULL CHECK (routine_type IN ('morning', 'evening'));

-- Add comment for clarity
COMMENT ON COLUMN public.task_templates.routine_type IS 'For routine tasks only: morning or evening. NULL for activities.';


-- ============================================================================
-- Migration 22: 20260114214011_8d258597-d4d3-4ed1-90ff-9f9db3a8223a.sql
-- ============================================================================

-- Add assignee_parent_id column for parent activities
-- When this is set and child_id is NULL, the task is for a parent
ALTER TABLE public.task_templates
ADD COLUMN assignee_parent_id UUID NULL;

-- Add comment explaining the usage
COMMENT ON COLUMN public.task_templates.assignee_parent_id IS
  'When set, indicates this task is assigned to a parent (adult). child_id should be NULL. The value references auth.users.id of the parent.';

-- Add index for efficient filtering
CREATE INDEX idx_task_templates_assignee_parent
ON public.task_templates(assignee_parent_id)
WHERE assignee_parent_id IS NOT NULL;


-- ============================================================================
-- Migration 23: 20260114220432_ea454d85-90e6-4659-9e11-bf4620950468.sql
-- ============================================================================

-- A) Add parent_activities_enabled to profiles for per-user control
ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS parent_activities_enabled boolean NOT NULL DEFAULT false;

-- C) Add color column to children for calendar item colors
ALTER TABLE public.children
ADD COLUMN IF NOT EXISTS color text DEFAULT '#3B82F6';

-- C) Add activity_color to profiles for adult activity colors
ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS activity_color text DEFAULT '#8B5CF6';

-- B) Create icon_library table for expanded icons
CREATE TABLE IF NOT EXISTS public.icon_library (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text UNIQUE NOT NULL,
  emoji text NOT NULL,
  name_en text NOT NULL,
  name_ru text NOT NULL,
  tags_en text[] DEFAULT '{}',
  tags_ru text[] DEFAULT '{}',
  category text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Enable RLS on icon_library
ALTER TABLE public.icon_library ENABLE ROW LEVEL SECURITY;

-- Icon library is public read for all authenticated users
CREATE POLICY "Authenticated users can view icons"
ON public.icon_library
FOR SELECT
TO authenticated
USING (true);

-- Insert expanded icon library with categories
INSERT INTO public.icon_library (key, emoji, name_en, name_ru, tags_en, tags_ru, category) VALUES
-- HOME category
('bed', '🛏️', 'Bed', 'Кровать', '{"bed","sleep","bedroom"}', '{"кровать","спать","спальня"}', 'home'),
('house', '🏠', 'House', 'Дом', '{"house","home"}', '{"дом","жильё"}', 'home'),
('door', '🚪', 'Door', 'Дверь', '{"door","entrance"}', '{"дверь","вход"}', 'home'),
('couch', '🛋️', 'Couch', 'Диван', '{"couch","sofa","furniture"}', '{"диван","мебель"}', 'home'),
('lamp', '💡', 'Lamp', 'Лампа', '{"lamp","light","bulb"}', '{"лампа","свет"}', 'home'),
('key', '🔑', 'Key', 'Ключ', '{"key","lock"}', '{"ключ","замок"}', 'home'),
('window', '🪟', 'Window', 'Окно', '{"window"}', '{"окно"}', 'home'),
('clock', '🕐', 'Clock', 'Часы', '{"clock","time"}', '{"часы","время"}', 'home'),
('alarm', '⏰', 'Alarm', 'Будильник', '{"alarm","wake","morning"}', '{"будильник","утро"}', 'home'),
('broom', '🧹', 'Broom', 'Метла', '{"broom","clean","sweep"}', '{"метла","уборка"}', 'home'),

-- HYGIENE category
('toothbrush', '🪥', 'Toothbrush', 'Зубная щётка', '{"toothbrush","teeth","dental","brush"}', '{"зубная щётка","зубы"}', 'hygiene'),
('shower', '🚿', 'Shower', 'Душ', '{"shower","bath","wash"}', '{"душ","мыться"}', 'hygiene'),
('bathtub', '🛁', 'Bathtub', 'Ванна', '{"bathtub","bath"}', '{"ванна","купаться"}', 'hygiene'),
('soap', '🧼', 'Soap', 'Мыло', '{"soap","wash","clean"}', '{"мыло","мыть"}', 'hygiene'),
('toilet', '🚽', 'Toilet', 'Туалет', '{"toilet","bathroom"}', '{"туалет","ванная"}', 'hygiene'),
('mirror', '🪞', 'Mirror', 'Зеркало', '{"mirror","reflection"}', '{"зеркало"}', 'hygiene'),
('razor', '🪒', 'Razor', 'Бритва', '{"razor","shave"}', '{"бритва","бриться"}', 'hygiene'),
('lotion', '🧴', 'Lotion', 'Лосьон', '{"lotion","cream","skincare"}', '{"лосьон","крем"}', 'hygiene'),
('comb', '💇', 'Hair', 'Причёска', '{"hair","comb","haircut"}', '{"волосы","причёска"}', 'hygiene'),
('hand_wash', '🧤', 'Hand wash', 'Мытьё рук', '{"hand","wash","hygiene"}', '{"руки","мыть"}', 'hygiene'),

-- FOOD category
('cooking', '🍳', 'Cooking', 'Готовка', '{"cooking","kitchen","frying"}', '{"готовка","кухня"}', 'food'),
('plate', '🍽️', 'Plate', 'Тарелка', '{"plate","dish","meal"}', '{"тарелка","еда"}', 'food'),
('apple', '🍎', 'Apple', 'Яблоко', '{"apple","fruit","healthy"}', '{"яблоко","фрукт"}', 'food'),
('banana', '🍌', 'Banana', 'Банан', '{"banana","fruit"}', '{"банан","фрукт"}', 'food'),
('carrot', '🥕', 'Carrot', 'Морковь', '{"carrot","vegetable"}', '{"морковь","овощ"}', 'food'),
('broccoli', '🥦', 'Broccoli', 'Брокколи', '{"broccoli","vegetable","healthy"}', '{"брокколи","овощ"}', 'food'),
('bread', '🍞', 'Bread', 'Хлеб', '{"bread","bakery"}', '{"хлеб","выпечка"}', 'food'),
('milk', '🥛', 'Milk', 'Молоко', '{"milk","dairy","drink"}', '{"молоко","молочное"}', 'food'),
('water', '💧', 'Water', 'Вода', '{"water","drink","hydration"}', '{"вода","пить"}', 'food'),
('juice', '🧃', 'Juice', 'Сок', '{"juice","drink","beverage"}', '{"сок","напиток"}', 'food'),
('cookie', '🍪', 'Cookie', 'Печенье', '{"cookie","sweet","snack"}', '{"печенье","сладкое"}', 'food'),
('cake', '🎂', 'Cake', 'Торт', '{"cake","birthday","dessert"}', '{"торт","десерт"}', 'food'),
('pizza', '🍕', 'Pizza', 'Пицца', '{"pizza","food"}', '{"пицца","еда"}', 'food'),
('salad', '🥗', 'Salad', 'Салат', '{"salad","healthy","vegetable"}', '{"салат","здоровое"}', 'food'),
('sandwich', '🥪', 'Sandwich', 'Бутерброд', '{"sandwich","lunch"}', '{"бутерброд","обед"}', 'food'),

-- SCHOOL/STUDY category
('book', '📚', 'Books', 'Книги', '{"book","read","study","library"}', '{"книги","чтение","учёба"}', 'school'),
('pencil', '✏️', 'Pencil', 'Карандаш', '{"pencil","write","draw"}', '{"карандаш","писать"}', 'school'),
('notebook', '📓', 'Notebook', 'Тетрадь', '{"notebook","write","notes"}', '{"тетрадь","заметки"}', 'school'),
('backpack', '🎒', 'Backpack', 'Рюкзак', '{"backpack","bag","school"}', '{"рюкзак","школа"}', 'school'),
('school', '🏫', 'School', 'Школа', '{"school","education"}', '{"школа","образование"}', 'school'),
('graduation', '🎓', 'Graduation', 'Выпускной', '{"graduation","education","cap"}', '{"выпускной","образование"}', 'school'),
('calculator', '🔢', 'Calculator', 'Калькулятор', '{"calculator","math","numbers"}', '{"калькулятор","математика"}', 'school'),
('globe', '🌍', 'Globe', 'Глобус', '{"globe","geography","world"}', '{"глобус","география"}', 'school'),
('microscope', '🔬', 'Microscope', 'Микроскоп', '{"microscope","science","lab"}', '{"микроскоп","наука"}', 'school'),
('computer', '💻', 'Computer', 'Компьютер', '{"computer","laptop","tech"}', '{"компьютер","ноутбук"}', 'school'),
('writing', '📝', 'Writing', 'Письмо', '{"writing","homework","note"}', '{"письмо","домашнее задание"}', 'school'),
('ruler', '📏', 'Ruler', 'Линейка', '{"ruler","measure","geometry"}', '{"линейка","геометрия"}', 'school'),
('abc', '🔤', 'ABC', 'Алфавит', '{"abc","alphabet","letters"}', '{"алфавит","буквы"}', 'school'),

-- SPORTS category
('soccer', '⚽', 'Soccer', 'Футбол', '{"soccer","football","ball","sport"}', '{"футбол","мяч","спорт"}', 'sports'),
('basketball', '🏀', 'Basketball', 'Баскетбол', '{"basketball","ball","sport"}', '{"баскетбол","мяч"}', 'sports'),
('tennis', '🎾', 'Tennis', 'Теннис', '{"tennis","ball","racket"}', '{"теннис","ракетка"}', 'sports'),
('swimming', '🏊', 'Swimming', 'Плавание', '{"swimming","pool","water"}', '{"плавание","бассейн"}', 'sports'),
('running', '🏃', 'Running', 'Бег', '{"running","exercise","jog"}', '{"бег","упражнение"}', 'sports'),
('cycling', '🚴', 'Cycling', 'Велосипед', '{"cycling","bike","bicycle"}', '{"велосипед","кататься"}', 'sports'),
('yoga', '🧘', 'Yoga', 'Йога', '{"yoga","meditation","stretch"}', '{"йога","медитация"}', 'sports'),
('gym', '🏋️', 'Gym', 'Тренажёрный зал', '{"gym","weights","exercise"}', '{"тренажёрка","зал"}', 'sports'),
('skating', '⛸️', 'Skating', 'Катание на коньках', '{"skating","ice","winter"}', '{"коньки","лёд"}', 'sports'),
('skiing', '⛷️', 'Skiing', 'Лыжи', '{"skiing","snow","winter"}', '{"лыжи","снег"}', 'sports'),
('martial_arts', '🥋', 'Martial Arts', 'Единоборства', '{"martial arts","karate","judo"}', '{"единоборства","карате"}', 'sports'),
('dance', '💃', 'Dance', 'Танцы', '{"dance","ballet","dancing"}', '{"танцы","балет"}', 'sports'),
('trophy', '🏆', 'Trophy', 'Трофей', '{"trophy","winner","prize"}', '{"трофей","приз"}', 'sports'),
('medal', '🥇', 'Medal', 'Медаль', '{"medal","gold","first"}', '{"медаль","золото"}', 'sports'),

-- CHORES category
('laundry', '👕', 'Laundry', 'Стирка', '{"laundry","clothes","wash"}', '{"стирка","одежда"}', 'chores'),
('vacuum', '🧹', 'Vacuum', 'Пылесос', '{"vacuum","clean","dust"}', '{"пылесос","чистить"}', 'chores'),
('trash', '🗑️', 'Trash', 'Мусор', '{"trash","garbage","bin"}', '{"мусор","выбросить"}', 'chores'),
('recycle', '♻️', 'Recycle', 'Переработка', '{"recycle","environment","eco"}', '{"переработка","экология"}', 'chores'),
('dishes', '🍽️', 'Dishes', 'Посуда', '{"dishes","wash","kitchen"}', '{"посуда","мыть"}', 'chores'),
('iron', '🧹', 'Iron', 'Глажка', '{"iron","clothes","press"}', '{"глажка","одежда"}', 'chores'),
('garden', '🌱', 'Garden', 'Сад', '{"garden","plant","grow"}', '{"сад","растение"}', 'chores'),
('watering', '💧', 'Watering', 'Полив', '{"watering","plants","garden"}', '{"полив","растения"}', 'chores'),
('organize', '📦', 'Organize', 'Организация', '{"organize","tidy","box"}', '{"организация","порядок"}', 'chores'),
('fold', '👔', 'Fold clothes', 'Сложить одежду', '{"fold","clothes","tidy"}', '{"сложить","одежда"}', 'chores'),
('make_bed', '🛏️', 'Make bed', 'Застелить кровать', '{"make bed","bedroom","morning"}', '{"застелить","кровать","утро"}', 'chores'),

-- FUN category
('game', '🎮', 'Gaming', 'Игры', '{"game","gaming","play","video"}', '{"игра","играть"}', 'fun'),
('puzzle', '🧩', 'Puzzle', 'Пазл', '{"puzzle","game","solve"}', '{"пазл","головоломка"}', 'fun'),
('art', '🎨', 'Art', 'Рисование', '{"art","paint","draw","creative"}', '{"рисование","творчество"}', 'fun'),
('music', '🎵', 'Music', 'Музыка', '{"music","song","listen"}', '{"музыка","песня"}', 'fun'),
('piano', '🎹', 'Piano', 'Пианино', '{"piano","keyboard","music"}', '{"пианино","клавиши"}', 'fun'),
('guitar', '🎸', 'Guitar', 'Гитара', '{"guitar","music","string"}', '{"гитара","музыка"}', 'fun'),
('movie', '🎬', 'Movie', 'Кино', '{"movie","film","watch"}', '{"кино","фильм"}', 'fun'),
('tv', '📺', 'TV', 'Телевизор', '{"tv","television","watch"}', '{"телевизор","смотреть"}', 'fun'),
('balloon', '🎈', 'Balloon', 'Шарик', '{"balloon","party","fun"}', '{"шарик","праздник"}', 'fun'),
('party', '🎉', 'Party', 'Вечеринка', '{"party","celebration"}', '{"вечеринка","праздник"}', 'fun'),
('gift', '🎁', 'Gift', 'Подарок', '{"gift","present","birthday"}', '{"подарок","сюрприз"}', 'fun'),
('teddy', '🧸', 'Teddy Bear', 'Мишка', '{"teddy","bear","toy","stuffed"}', '{"мишка","игрушка"}', 'fun'),
('blocks', '🧱', 'Blocks', 'Кубики', '{"blocks","lego","build"}', '{"кубики","лего","строить"}', 'fun'),
('kite', '🪁', 'Kite', 'Воздушный змей', '{"kite","fly","outdoor"}', '{"змей","летать"}', 'fun'),
('playground', '🛝', 'Playground', 'Площадка', '{"playground","park","play"}', '{"площадка","парк"}', 'fun'),
('reading', '📖', 'Reading', 'Чтение', '{"reading","book","story"}', '{"чтение","книга"}', 'fun'),
('magic', '✨', 'Magic', 'Магия', '{"magic","sparkle","special"}', '{"магия","волшебство"}', 'fun'),
('rainbow', '🌈', 'Rainbow', 'Радуга', '{"rainbow","colorful"}', '{"радуга","цветной"}', 'fun'),

-- PETS category
('dog', '🐕', 'Dog', 'Собака', '{"dog","pet","walk"}', '{"собака","питомец"}', 'pets'),
('cat', '🐈', 'Cat', 'Кошка', '{"cat","pet","kitten"}', '{"кошка","кот","питомец"}', 'pets'),
('fish', '🐠', 'Fish', 'Рыбка', '{"fish","aquarium","pet"}', '{"рыбка","аквариум"}', 'pets'),
('hamster', '🐹', 'Hamster', 'Хомяк', '{"hamster","pet","rodent"}', '{"хомяк","питомец"}', 'pets'),
('rabbit', '🐰', 'Rabbit', 'Кролик', '{"rabbit","bunny","pet"}', '{"кролик","зайчик"}', 'pets'),
('bird', '🐦', 'Bird', 'Птица', '{"bird","parrot","pet"}', '{"птица","попугай"}', 'pets'),
('turtle', '🐢', 'Turtle', 'Черепаха', '{"turtle","pet","slow"}', '{"черепаха","питомец"}', 'pets'),
('paw', '🐾', 'Paw', 'Лапка', '{"paw","pet","print"}', '{"лапка","след"}', 'pets'),
('bone', '🦴', 'Bone', 'Косточка', '{"bone","dog","treat"}', '{"косточка","собака"}', 'pets'),
('leash', '🦮', 'Walk dog', 'Прогулка с собакой', '{"walk","dog","leash"}', '{"прогулка","собака"}', 'pets'),

-- TRAVEL category
('car', '🚗', 'Car', 'Машина', '{"car","drive","vehicle"}', '{"машина","авто"}', 'travel'),
('bus', '🚌', 'Bus', 'Автобус', '{"bus","transport","public"}', '{"автобус","транспорт"}', 'travel'),
('train', '🚆', 'Train', 'Поезд', '{"train","railway","travel"}', '{"поезд","железная дорога"}', 'travel'),
('plane', '✈️', 'Plane', 'Самолёт', '{"plane","airplane","fly"}', '{"самолёт","лететь"}', 'travel'),
('boat', '⛵', 'Boat', 'Лодка', '{"boat","sail","water"}', '{"лодка","парусник"}', 'travel'),
('beach', '🏖️', 'Beach', 'Пляж', '{"beach","sand","vacation"}', '{"пляж","песок","отпуск"}', 'travel'),
('mountain', '🏔️', 'Mountain', 'Гора', '{"mountain","hiking","nature"}', '{"гора","поход"}', 'travel'),
('camping', '🏕️', 'Camping', 'Кемпинг', '{"camping","tent","outdoor"}', '{"кемпинг","палатка"}', 'travel'),
('luggage', '🧳', 'Luggage', 'Багаж', '{"luggage","suitcase","travel"}', '{"багаж","чемодан"}', 'travel'),
('map', '🗺️', 'Map', 'Карта', '{"map","navigation","travel"}', '{"карта","навигация"}', 'travel'),

-- HEALTH category
('doctor', '👨‍⚕️', 'Doctor', 'Доктор', '{"doctor","health","medical"}', '{"доктор","здоровье"}', 'health'),
('medicine', '💊', 'Medicine', 'Лекарство', '{"medicine","pill","health"}', '{"лекарство","таблетка"}', 'health'),
('thermometer', '🌡️', 'Thermometer', 'Термометр', '{"thermometer","temperature","sick"}', '{"термометр","температура"}', 'health'),
('bandage', '🩹', 'Bandage', 'Пластырь', '{"bandage","injury","first aid"}', '{"пластырь","рана"}', 'health'),
('sleep', '😴', 'Sleep', 'Сон', '{"sleep","rest","night"}', '{"сон","отдых","ночь"}', 'health'),
('meditation', '🧘', 'Meditation', 'Медитация', '{"meditation","calm","relax"}', '{"медитация","релакс"}', 'health'),
('heart', '❤️', 'Heart', 'Сердце', '{"heart","love","health"}', '{"сердце","любовь"}', 'health'),
('brain', '🧠', 'Brain', 'Мозг', '{"brain","think","smart"}', '{"мозг","думать"}', 'health'),
('vitamins', '💪', 'Vitamins', 'Витамины', '{"vitamins","strong","health"}', '{"витамины","сила"}', 'health'),

-- OTHER/GENERAL category
('star', '⭐', 'Star', 'Звезда', '{"star","favorite","special"}', '{"звезда","любимое"}', 'other'),
('sparkle', '✨', 'Sparkle', 'Блеск', '{"sparkle","magic","shine"}', '{"блеск","магия"}', 'other'),
('sun', '☀️', 'Sun', 'Солнце', '{"sun","morning","bright"}', '{"солнце","утро"}', 'other'),
('moon', '🌙', 'Moon', 'Луна', '{"moon","night","sleep"}', '{"луна","ночь"}', 'other'),
('check', '✅', 'Check', 'Галочка', '{"check","done","complete"}', '{"галочка","готово"}', 'other'),
('fire', '🔥', 'Fire', 'Огонь', '{"fire","hot","urgent"}', '{"огонь","срочно"}', 'other'),
('lightning', '⚡', 'Lightning', 'Молния', '{"lightning","fast","energy"}', '{"молния","быстро"}', 'other'),
('target', '🎯', 'Target', 'Цель', '{"target","goal","aim"}', '{"цель","достигнуть"}', 'other'),
('bell', '🔔', 'Bell', 'Колокольчик', '{"bell","notification","ring"}', '{"колокольчик","уведомление"}', 'other'),
('calendar', '📅', 'Calendar', 'Календарь', '{"calendar","date","schedule"}', '{"календарь","дата"}', 'other'),
('timer', '⏱️', 'Timer', 'Таймер', '{"timer","stopwatch","time"}', '{"таймер","время"}', 'other'),
('money', '💰', 'Money', 'Деньги', '{"money","coins","reward"}', '{"деньги","монеты"}', 'other'),
('lightbulb', '💡', 'Idea', 'Идея', '{"idea","lightbulb","think"}', '{"идея","лампочка"}', 'other'),
('thumbs_up', '👍', 'Thumbs Up', 'Класс', '{"thumbs up","like","good"}', '{"класс","нравится"}', 'other'),
('clap', '👏', 'Clap', 'Аплодисменты', '{"clap","applause","bravo"}', '{"аплодисменты","браво"}', 'other'),
('crown', '👑', 'Crown', 'Корона', '{"crown","king","queen","royalty"}', '{"корона","король"}', 'other'),
('phone', '📱', 'Phone', 'Телефон', '{"phone","mobile","call"}', '{"телефон","звонок"}', 'other'),
('email', '📧', 'Email', 'Почта', '{"email","mail","message"}', '{"почта","письмо"}', 'other'),
('chat', '💬', 'Chat', 'Чат', '{"chat","message","talk"}', '{"чат","сообщение"}', 'other'),
('question', '❓', 'Question', 'Вопрос', '{"question","ask","help"}', '{"вопрос","помощь"}', 'other'),
('warning', '⚠️', 'Warning', 'Внимание', '{"warning","caution","alert"}', '{"внимание","осторожно"}', 'other'),
('lock', '🔒', 'Lock', 'Замок', '{"lock","secure","private"}', '{"замок","безопасность"}', 'other'),
('folder', '📁', 'Folder', 'Папка', '{"folder","file","organize"}', '{"папка","файл"}', 'other'),
('settings', '⚙️', 'Settings', 'Настройки', '{"settings","gear","configure"}', '{"настройки","параметры"}', 'other'),
('search', '🔍', 'Search', 'Поиск', '{"search","find","magnify"}', '{"поиск","найти"}', 'other'),
('link', '🔗', 'Link', 'Ссылка', '{"link","chain","connect"}', '{"ссылка","связь"}', 'other'),
('rocket', '🚀', 'Rocket', 'Ракета', '{"rocket","launch","fast"}', '{"ракета","запуск"}', 'other'),
('world', '🌎', 'World', 'Мир', '{"world","earth","globe"}', '{"мир","земля"}', 'other'),
('flag', '🚩', 'Flag', 'Флаг', '{"flag","goal","mark"}', '{"флаг","цель"}', 'other'),
('ribbon', '🎀', 'Ribbon', 'Бантик', '{"ribbon","bow","gift"}', '{"бантик","подарок"}', 'other'),
('camera', '📷', 'Camera', 'Камера', '{"camera","photo","picture"}', '{"камера","фото"}', 'other'),
('microphone', '🎤', 'Microphone', 'Микрофон', '{"microphone","sing","speak"}', '{"микрофон","петь"}', 'other'),
('headphones', '🎧', 'Headphones', 'Наушники', '{"headphones","listen","music"}', '{"наушники","слушать"}', 'other')
ON CONFLICT (key) DO NOTHING;

-- Create indexes for faster searching
CREATE INDEX IF NOT EXISTS idx_icon_library_category ON public.icon_library(category);
CREATE INDEX IF NOT EXISTS idx_icon_library_tags_en ON public.icon_library USING GIN(tags_en);
CREATE INDEX IF NOT EXISTS idx_icon_library_tags_ru ON public.icon_library USING GIN(tags_ru);


-- ============================================================================
-- Migration 24: 20260116061406_afb545b1-382f-4886-8ea5-17403d1aa041.sql
-- ============================================================================

-- Allow pending invites without a user_id
ALTER TABLE public.family_members
  ALTER COLUMN user_id DROP NOT NULL;

-- Replace the hard unique constraint with a partial unique index
ALTER TABLE public.family_members
  DROP CONSTRAINT IF EXISTS family_members_family_id_user_id_key;

CREATE UNIQUE INDEX IF NOT EXISTS family_members_unique_accepted
  ON public.family_members (family_id, user_id)
  WHERE invite_status = 'accepted' AND user_id IS NOT NULL;

-- Speed up invite token lookup
CREATE INDEX IF NOT EXISTS family_members_invite_token_idx
  ON public.family_members (invite_token);

-- Accept an invite token and attach it to the current authenticated user
CREATE OR REPLACE FUNCTION public.accept_family_invite(p_token uuid)
RETURNS TABLE (family_id uuid, permission_level text, role_label text)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_invite public.family_members%ROWTYPE;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  SELECT *
    INTO v_invite
  FROM public.family_members
  WHERE invite_token = p_token
    AND invite_status = 'pending'
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Invalid or expired invite';
  END IF;

  -- If already a member, invalidate the token row and return
  IF EXISTS (
    SELECT 1
    FROM public.family_members
    WHERE family_id = v_invite.family_id
      AND user_id = auth.uid()
      AND invite_status = 'accepted'
  ) THEN
    UPDATE public.family_members
      SET invite_status = 'declined',
          invite_token = NULL,
          updated_at = now()
    WHERE id = v_invite.id;

    RETURN QUERY
      SELECT v_invite.family_id, v_invite.permission_level, v_invite.role_label;
    RETURN;
  END IF;

  UPDATE public.family_members
    SET user_id = auth.uid(),
        invite_status = 'accepted',
        invite_token = NULL,
        updated_at = now()
  WHERE id = v_invite.id;

  RETURN QUERY
    SELECT v_invite.family_id, v_invite.permission_level, v_invite.role_label;
END;
$$;

GRANT EXECUTE ON FUNCTION public.accept_family_invite(uuid) TO authenticated;


-- ============================================================================
-- Migration 25: 20260116063410_f2f5133f-c122-41ea-b4e2-79d69baf6dfc.sql
-- ============================================================================

-- Add job_claim_id column to task_instances for stable job-task linking
ALTER TABLE public.task_instances
ADD COLUMN job_claim_id uuid NULL REFERENCES public.job_claims(id) ON DELETE SET NULL;

-- Create unique index to prevent duplicate task instances per job claim
CREATE UNIQUE INDEX task_instances_unique_job_claim
ON public.task_instances (job_claim_id)
WHERE job_claim_id IS NOT NULL;

-- Create index for faster job claim lookups
CREATE INDEX task_instances_job_claim_id_idx
ON public.task_instances (job_claim_id)
WHERE job_claim_id IS NOT NULL;
